# Generated by Django 4.0.5 on 2022-07-27 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tableintersetmodel_tableeventmodel_tableactionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_realizada', models.CharField(choices=[('Apoio Técnico Presencial (ATP)', 'Apoio Técnico Presencial (ATP)'), ('Apoio Técnico Não Presencial (ATNP)', 'Apoio Técnico Não Presencial (ATNP)'), ('Outras Ações', 'Outras Ações')], default='Apoio Técnico Presencial (ATP)', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoAcoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
